export const deliveryOrders = [
  {
    id: 1,
    orderNumber: "#ORD-2840",
    from: "McDonald's",
    fromAddress: "145 Main St, Downtown",
    to: "328 Oak Avenue, Apt 5B",
    price: " ₦18.50",
    distance: "2.3 mi",
    eta: "15 min",
    pickupTime: "2:30 PM",
  },
  {
    id: 2,
    orderNumber: "#ORD-2841",
    from: "Pizza Hut",
    fromAddress: "892 Broadway, Suite 12",
    to: "156 Maple Drive",
    price: " ₦24.75",
    distance: "3.8 mi",
    eta: "22 min",
    pickupTime: "3:15 PM",
  },
  {
    id: 3,
    orderNumber: "#ORD-2842",
    from: "Starbucks",
    fromAddress: "421 Park Boulevard",
    to: "789 Pine Road, Building C",
    price: " ₦12.25",
    distance: "1.2 mi",
    eta: "10 min",
    pickupTime: "2:45 PM",
  },
  {
    id: 4,
    orderNumber: "#ORD-2843",
    from: "Chipotle",
    fromAddress: "567 Washington Ave",
    to: "234 Cedar Lane",
    price: " ₦21.90",
    distance: "4.5 mi",
    eta: "28 min",
    pickupTime: "3:00 PM",
  },
  {
    id: 5,
    orderNumber: "#ORD-2844",
    from: "KFC",
    fromAddress: "103 Lake View Drive",
    to: "445 River Road, Unit 8",
    price: " ₦16.40",
    distance: "2.7 mi",
    eta: "18 min",
    pickupTime: "2:50 PM",
  },
  {
    id: 6,
    orderNumber: "#ORD-2845",
    from: "Subway",
    fromAddress: "298 Hill Street",
    to: "621 Elm Street",
    price: " ₦14.80",
    distance: "1.9 mi",
    eta: "12 min",
    pickupTime: "3:10 PM",
  },
  {
    id: 7,
    orderNumber: "#ORD-2846",
    from: "Burger King",
    fromAddress: "734 Lincoln Road",
    to: "890 Madison Street, Apt 12A",
    price: " ₦19.65",
    distance: "3.1 mi",
    eta: "20 min",
    pickupTime: "3:20 PM",
  },
  {
    id: 8,
    orderNumber: "#ORD-2847",
    from: "Taco Bell",
    fromAddress: "512 Market Street",
    to: "167 Church Avenue",
    price: " ₦13.50",
    distance: "1.6 mi",
    eta: "11 min",
    pickupTime: "2:55 PM",
  },
  {
    id: 9,
    orderNumber: "#ORD-2848",
    from: "Domino's Pizza",
    fromAddress: "876 School Road",
    to: "943 Mill Street, Suite 3",
    price: " ₦27.30",
    distance: "5.2 mi",
    eta: "32 min",
    pickupTime: "3:25 PM",
  },
  {
    id: 10,
    orderNumber: "#ORD-2849",
    from: "Panera Bread",
    fromAddress: "654 Bridge Lane",
    to: "278 Jefferson Drive",
    price: " ₦15.95",
    distance: "2.1 mi",
    eta: "14 min",
    pickupTime: "3:05 PM",
  },
  {
    id: 11,
    orderNumber: "#ORD-2850",
    from: "Shake Shack",
    fromAddress: "321 Grove Street",
    to: "556 Sunset Boulevard, Apt 7C",
    price: " ₦22.40",
    distance: "3.6 mi",
    eta: "24 min",
    pickupTime: "3:30 PM",
  },
  {
    id: 12,
    orderNumber: "#ORD-2851",
    from: "Five Guys",
    fromAddress: "198 Valley Road",
    to: "834 Highland Avenue",
    price: " ₦20.10",
    distance: "2.9 mi",
    eta: "19 min",
    pickupTime: "3:12 PM",
  },
];
